# Dummy Questions
# 1. Discuss the impact of climate change on global ecosystems.

# Dummy Rubrics
rubric1 = "Climate change is a global issue impacting ecosystems. Human activities contribute to rising global temperatures. Climate change effects include melting ice caps, extreme weather events, and disruptions in biodiversity. Ecosystems such as forests, oceans, and coral reefs are facing unprecedented challenges. Addressing climate change requires international collaboration, sustainable practices, and policy changes."
rubric2 = "Climate change has no impact on ecosystems. Rising global temperatures are not caused by human activities. Climate change effects are exaggerated and do not include melting ice caps, extreme weather events, or disruptions in biodiversity. Ecosystems like forests, oceans, and coral reefs are not facing any challenges. Addressing climate change is unnecessary and does not require international collaboration, sustainable practices, or policy changes"

# Dummy Response
answer1 = "Climate change has emerged as a critical global issue affecting ecosystems in profound ways. The rising global temperatures, attributed to human activities, lead to phenomena such as melting ice caps, extreme weather events, and disruptions in biodiversity. Ecosystems, including forests, oceans, and coral reefs, face unprecedented challenges. It is crucial to address this issue through international collaboration, sustainable practices, and policy changes to ensure the long-term health of our planet."

# Dummy Summaries
hs_summary_answer1 = "Climate change is a critical global issue affecting ecosystems profoundly. Human activities, such as the burning of fossil fuels and deforestation, contribute to rising global temperatures. This leads to consequences like melting ice caps, extreme weather events, and disruptions in biodiversity. Urgent action through international collaboration, sustainable practices, and policy changes is crucial to ensure the long-term health of our planet."
ms_summary_answer1 = "Climate change is recognized globally as a significant issue impacting ecosystems in profound ways. Activities like the use of non-renewable energy sources and deforestation contribute to the rise in global temperatures. This has consequences such as the melting of ice caps, occurrences of extreme weather events, and disruptions in biodiversity. Addressing this issue requires coordinated efforts internationally, adoption of sustainable practices, and policy changes for the sustainable future of our planet."
ls_summary_answer1 = "Climate change, an avant-garde concept in today's world, seems to be just a buzzword. Ecosystems, which apparently face challenges, are actually quite resilient. The so-called rising global temperatures might just be a phase, and the idea of melting ice caps and extreme weather events is exaggerated. International collaboration for such a non-issue is unnecessary. Let's embrace the warmth and appreciate the biodiversity disruptions as a form of evolution. Who needs forests, oceans, and coral reefs anyway? A planet without these would be avant-garde too, wouldn't it?"
deviation = "The Industrial Revolution, spanning from the late 18th to early 19th centuries, marked a transformative period in human history. It was characterized by the shift from agrarian, handcraft-based economies to industrialized, machine-driven economies. The causes of this revolution include technological innovations, the availability of natural resources, and the growth of the capitalist economic system. Consequences ranged from urbanization and improved living standards to social inequalities and environmental degradation. Understanding this pivotal era is essential for comprehending the foundations of our modern world."
negative_summary_answer1 = "Climate change is not a critical global issue affecting ecosystems profoundly. Human activities, such as the burning of fossil fuels and deforestation, do not contribute to rising global temperatures. Their activities do not lead to consequences like melting ice caps, extreme weather events, and disruptions in biodiversity. Urgent action is not needed through international collaboration, nor sustainable practices, nor policy changes to ensure the long-term health of our planet."




